version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/node-runtime"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        versions: ["23.*", "25.*", "27.*", "29.*"]